"""YoutubeCommentAnalysis add index

Revision ID: 07843b52a619
Revises: 38a4a1dc8963
Create Date: 2025-08-12 03:29:27.527902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07843b52a619'
down_revision = '38a4a1dc8963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_comment_analysis', schema=None) as batch_op:
        batch_op.create_index('idx_comment_analysis_comment_time', ['comment_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_comment_analysis_crypto_time', ['crypto_symbol', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_comment_analysis', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_analysis_crypto_time')
        batch_op.drop_index('idx_comment_analysis_comment_time')

    # ### end Alembic commands ###
