"""create_sentiment_aggregate_model

Revision ID: 2feb84060e15
Revises: ffa1dc3abc3c
Create Date: 2025-07-20 11:55:51.735046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2feb84060e15'
down_revision = 'ffa1dc3abc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_sentiment_aggregate_data',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('normalised_up_percentage', sa.Float(), nullable=False),
    sa.Column('normalised_down_percentage', sa.Float(), nullable=False),
    sa.Column('avg_positive_sentiment', sa.Float(), nullable=False),
    sa.Column('avg_neutral_sentiment', sa.Float(), nullable=False),
    sa.Column('avg_negative_sentiment', sa.Float(), nullable=False),
    sa.Column('avg_compound_sentiment', sa.Float(), nullable=False),
    sa.Column('earliest_post', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['crypto_asset.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    with op.batch_alter_table('crypto_sentiment_aggregate_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crypto_sentiment_aggregate_data_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_sentiment_aggregate_data')
    # ### end Alembic commands ###
