"""create_news_model

Revision ID: 33a513f0345e
Revises: d5543f256314
Create Date: 2025-07-22 23:48:41.316289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33a513f0345e'
down_revision = 'd5543f256314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_news_data',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['crypto_asset.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'source_url')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_news_data')
    # ### end Alembic commands ###
