"""create_reddit_model

Revision ID: af3b21ce4448
Revises: f1cd60933ca5
Create Date: 2025-07-17 21:25:25.103779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af3b21ce4448'
down_revision = 'f1cd60933ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_reddit_data',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('subreddit', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['crypto_source.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['crypto_asset.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'subreddit', 'text', 'timestamp')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_reddit_data')
    # ### end Alembic commands ###
