"""Adds crypto tech indicator table

Revision ID: bbfa3ff35eb2
Revises: 2feb84060e15
Create Date: 2025-07-21 00:33:16.958190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfa3ff35eb2'
down_revision = '2feb84060e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_technical_indicator',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ema', sa.Numeric(), nullable=True),
    sa.Column('macd', sa.Numeric(), nullable=True),
    sa.Column('rsi', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['crypto_asset.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'interval')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_technical_indicator')
    # ### end Alembic commands ###
