"""Create UserProfile model

Revision ID: c5e9bad0b632
Revises: 187a16d54d5a
Create Date: 2025-06-29 23:06:27.002842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c5e9bad0b632'
down_revision = '187a16d54d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types if they don't exist using postgresql.ENUM with create_type=False
    time_score_enum = postgresql.ENUM('SHORT', 'MEDIUM', 'LONG', name='timescore', create_type=False)
    social_impact_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='socialimpact', create_type=False)
    investor_type_enum = postgresql.ENUM('CAUTIOUS_PRESERVER', 'ADVENTURE_SEEKER', 'DATA_DRIVEN_STRATEGIST', 'EMOTIONAL_EXPLORER', 'BALANCED_LEARNER', name='investortype', create_type=False)
    
    # Create enums only if they don't exist
    import psycopg2
    try:
        postgresql.ENUM('SHORT', 'MEDIUM', 'LONG', name='timescore').create(op.get_bind())
    except psycopg2.errors.DuplicateObject:
        pass  # Enum already exists
    
    try:
        postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='socialimpact').create(op.get_bind())
    except psycopg2.errors.DuplicateObject:
        pass  # Enum already exists
        
    try:
        postgresql.ENUM('CAUTIOUS_PRESERVER', 'ADVENTURE_SEEKER', 'DATA_DRIVEN_STRATEGIST', 'EMOTIONAL_EXPLORER', 'BALANCED_LEARNER', name='investortype').create(op.get_bind())
    except psycopg2.errors.DuplicateObject:
        pass  # Enum already exists
    
    op.create_table('user_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('rational_score', sa.Integer(), nullable=False),
    sa.Column('fomo_score', sa.Integer(), nullable=False),
    sa.Column('emotional_score', sa.Integer(), nullable=False),
    sa.Column('time_score', time_score_enum, nullable=True),
    sa.Column('social_impact', social_impact_enum, nullable=True),
    sa.Column('investor_type', investor_type_enum, nullable=True),
    sa.Column('raw_responses', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
