"""Added marketcap and volume to crypto asset

Revision ID: cb1fb464822e
Revises: c530bf29fb43
Create Date: 2025-08-05 04:20:15.909264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1fb464822e'
down_revision = 'c530bf29fb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketcap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_asset', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('marketcap')

    # ### end Alembic commands ###
