"""added subscription tier for usermodel

Revision ID: cf49dc4e08f3
Revises: 33a513f0345e
Create Date: 2025-07-29 21:45:04.008715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf49dc4e08f3'
down_revision = '33a513f0345e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
