"""Create YoutubeComment

Revision ID: f14ddc1620e6
Revises: bbfa3ff35eb2
Create Date: 2025-07-22 21:11:48.100031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14ddc1620e6'
down_revision = 'bbfa3ff35eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_comment',
    sa.Column('comment_id', sa.String(length=50), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('video_title', sa.String(length=255), nullable=False),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('total_reply_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('youtube_comment', schema=None) as batch_op:
        batch_op.create_index('idx_comment_video_published', ['video_id', 'published_at'], unique=False)

    with op.batch_alter_table('crypto_source', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_crypto_source_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_source', schema=None) as batch_op:
        batch_op.drop_constraint('uq_crypto_source_id', type_='unique')

    with op.batch_alter_table('youtube_comment', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_video_published')

    op.drop_table('youtube_comment')
    # ### end Alembic commands ###
