"""create_coingecko_model

Revision ID: f1cd60933ca5
Revises: 4470b2a3014b
Create Date: 2025-07-17 21:14:08.446344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f1cd60933ca5'
down_revision = '4470b2a3014b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('crypto_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('categories', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('coingecko_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('homepage_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subreddit_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('purchase_platforms', sa.TEXT(), autoincrement=False, nullable=True))
    
    op.create_table('crypto_coingecko_sentiment_data',
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sentiment_up_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sentiment_down_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reddit_average_posts_48h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('commit_count_4_weeks', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['crypto_asset.symbol'], name=op.f('crypto_coingecko_sentiment_data_symbol_fkey')),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', name=op.f('crypto_coingecko_sentiment_data_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_coingecko_sentiment_data')
    with op.batch_alter_table('crypto_asset', schema=None) as batch_op:
        batch_op.drop_column('coingecko_id')
        batch_op.drop_column('image')
        batch_op.drop_column('description')
        batch_op.drop_column('categories')
        batch_op.drop_column('homepage_url')
        batch_op.drop_column('subreddit_url')
        batch_op.drop_column('purchase_platforms')

    # ### end Alembic commands ###
